FROM nginx:mainline-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY assets/react-resume-app /usr/share/nginx/html
COPY assets/docker.nginx /etc/nginx/nginx.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
