FROM nginx:1.24-alpine3.17

RUN rm /etc/nginx/conf.d/default.conf

COPY assets/react-resume-app /usr/share/nginx/html
COPY assets/10.docker.nginx /etc/nginx/nginx.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
